apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: details-app
  template:
    metadata:
      labels:
        app: details-app
    spec:
      containers:
      - name: details-app
        image: meir25/details-app:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: details-app-service
spec:
  selector:
    app: details-app
  ports:
  - port: 80
    targetPort: 80
    nodePort: 8085
  type: NodePort

